//
//  DirectivePayload.swift
//  DragsterOS
//
//  Created by James Parker on 28/02/2026.
//


import Foundation
import SwiftData

// 1. The Decodable Bridge
struct DirectivePayload: Codable {
    let assignedDate: Date
    let discipline: String
    let missionTitle: String
    let missionNotes: String
    let warmupMinutes: Int
    let intervalSets: Int
    let workDurationMinutes: Int
    let workTargetWatts: Int
    let recoveryDurationMinutes: Int
    let cooldownMinutes: Int
        let fuelTier: String     // ✨ Now explicitly decoding
            let targetLoad: Int      // ✨ Now explicitly decoding
            let coachNotes: String   // ✨ Now explicitly decoding
}

class MissionIngestionService {
    static let shared = MissionIngestionService()
    private init() {}
    
    /// Parses the Custom Gem JSON and saves it directly to SwiftData
    func ingest(jsonString: String, context: ModelContext) throws -> Int {
        guard let data = jsonString.data(using: .utf8) else {
            throw NSError(domain: "Ingestion", code: 1, userInfo: [NSLocalizedDescriptionKey: "Invalid string encoding."])
        }
        
        let decoder = JSONDecoder()
        // Crucial: Tell Swift how to read the dates generated by the Gem
        decoder.dateDecodingStrategy = .iso8601 
        
        // Decode the JSON array into our bridging structs
        let payloads = try decoder.decode([DirectivePayload].self, from: data)
        
        // Convert and insert into the SwiftData context
        for payload in payloads {
            let newDirective = OperationalDirective(
                assignedDate: payload.assignedDate,
                discipline: payload.discipline,
                missionTitle: payload.missionTitle,
                missionNotes: payload.missionNotes,
                warmupMinutes: payload.warmupMinutes,
                intervalSets: payload.intervalSets,
                workDurationMinutes: payload.workDurationMinutes,
                workTargetWatts: payload.workTargetWatts,
                recoveryDurationMinutes: payload.recoveryDurationMinutes,
                cooldownMinutes: payload.cooldownMinutes,
                fuelTier: payload.fuelTier,
                targetLoad: payload.targetLoad,   // <-- THIS MUST BE MAPPED
                coachNotes: payload.coachNotes    // <-- THIS MUST BE MAPPED
            )
            context.insert(newDirective)
        }
        
        try context.save()
        return payloads.count // Returns the number of missions successfully imported
    }
}
